### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Forbidden

### ISSUE THREAD

**Issue by LinqLover** [mmichailidis/sendgrid-mail-action#3]
```
Run mmichailidis/sendgrid-mail-action@v1.0
  with:
    sendgrid-token: ***
    mail: ***
    subject: some clever text
    from: sendgridmailaction@github.com
    individual: false
    text: The following action $ACTION$ produced an event $EVENT$
    splitterator: ,
(node:2496) UnhandledPromiseRejectionWarning: Error: Forbidden
    at Request._callback (/home/runner/work/_actions/mmichailidis/sendgrid-mail-action/v1.0/dist/index.js:13316:25)
    at Request.self.callback (/home/runner/work/_actions/mmichailidis/sendgrid-mail-action/v1.0/dist/index.js:27566:22)
    at Request.emit (events.js:210:5)
    at Request.<anonymous> (/home/runner/work/_actions/mmichailidis/sendgrid-mail-action/v1.0/dist/index.js:28542:10)
    at Request.emit (events.js:210:5)
    at IncomingMessage.<anonymous> (/home/runner/work/_actions/mmichailidis/sendgrid-mail-action/v1.0/dist/index.js:28464:12)
    at Object.onceWrapper (events.js:299:28)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(node:2496) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2496) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Despite the error, the exit code of the action is zero.

**Comment by mmichailidis** [comment]
The exception is no longer suppressed as it was. Feel free to reopen if required

**Comment by LinqLover** [comment]
Thanks. Still, I got a Forbidden error but using sendgrid in a local shell worked for me ...

**Comment by mmichailidis** [comment]
Yes this happens due to a change to SendGrid policy and you have to verify your sender mail before sending a mail using that domain.
